export const ALL_CATEGORIES_REQUEST = "ALL_CATEGORIES_REQUEST";
export const ALL_CATEGORIES_SUCCESS = "ALL_CATEGORIES_SUCCESS";
export const ALL_CATEGORIES_FAIL = "ALL_CATEGORIES_FAIL";

export const CREATE_CATEGORIES_REQUEST = "CREATE_CATEGORIES_REQUEST";
export const CREATE_CATEGORIES_SUCCESS = "CREATE_CATEGORIES_SUCCESS";
export const CREATE_CATEGORIES_FAIL = "CREATE_CATEGORIES_FAIL";

export const ADMIN_CATEGORIES_DETAIL_REQUEST =
  "ADMIN_CATEGORIES_DETAIL_REQUEST";
export const ADMIN_CATEGORIES_DETAIL_SUCCESS =
  "ADMIN_CATEGORIES_DETAIL_SUCCESS";
export const ADMIN_CATEGORIES_DETAIL_FAIL = "ADMIN_CATEGORIES_DETAIL_FAIL";

export const EDIT_CATEGORIES_REQUEST = "EDIT_CATEGORIES_REQUEST";
export const EDIT_CATEGORIES_SUCCESS = "EDIT_CATEGORIES_SUCCESS";
export const EDIT_CATEGORIES_FAIL = "EDIT_CATEGORIES_FAIL";

export const DELETE_CATEGORIES_REQUEST = "DELETE_CATEGORIES_REQUEST";
export const DELETE_CATEGORIES_SUCCESS = "DELETE_CATEGORIES_SUCCESS";
export const DELETE_CATEGORIES_FAIL = "DELETE_CATEGORIES_FAIL";
