export const ALL_CUSTOMERS_REQUEST = "ALL_CUSTOMERS_REQUEST";
export const ALL_CUSTOMERS_SUCCESS = "ALL_CUSTOMERS_SUCCESS";
export const ALL_CUSTOMERS_FAIL = "ALL_CUSTOMERS_FAIL";

export const DELETE_CUSTOMERS_REQUEST = "DELETE_CUSTOMERS_REQUEST";
export const DELETE_CUSTOMERS_SUCCESS = "DELETE_CUSTOMERS_SUCCESS";
export const DELETE_CUSTOMERS_FAIL = "DELETE_CUSTOMERS_FAIL";
