export const ALL_ORDERS_REQUEST = "ALL_ORDERS_REQUEST";
export const ALL_ORDERS_SUCCESS = "ALL_ORDERS_SUCCESS";
export const ALL_ORDERS_FAIL = "ALL_ORDERS_FAIL";

export const ADMIN_ORDER_DETAIL_REQUEST = "ADMIN_ORDER_DETAIL_REQUEST";
export const ADMIN_ORDER_DETAIL_SUCCESS = "ADMIN_ORDER_DETAIL_SUCCESS";
export const ADMIN_ORDER_DETAIL_FAIL = "ADMIN_ORDER_DETAIL_FAIL";

export const EDIT_ORDER_REQUEST = "EDIT_ORDER_REQUEST";
export const EDIT_ORDER_SUCCESS = "EDIT_ORDER_SUCCESS";
export const EDIT_ORDER_FAIL = "EDIT_ORDER_FAIL";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";
